# -*- coding: utf-8 -*-
"""Ex_Functions_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2HPFcVskw-K0LACfA2jRM54CxNPfIMN
"""

def say_hello():
  return "Hello, world!"

say_hello()

def check_weather():
  weather = "raining"
  if weather == "sunny":
    print("It's a sunny day! Enjoy!")
  else:
    print('It might rain. Take an umbrella!')

check_weather()

def introduce_pet(cat_name, dog_name):
  return f"Please meet my cat named {cat_name} and my dog named {dog_name}."

print (introduce_pet("Cleo", "Bambou"))
print(introduce_pet(dog_name="Bambou",cat_name="Cleo"))

def greet_person(name,age=25):
  return f"Hello, {name}! You are {age} years old."

print(greet_person("Bruno",3))

#EX1

 def add_two_numbers(a,b):
  return a+b

print(add_two_numbers(15,10))

#EX2

def greet(name):
  return f"Hello, {name}!"

print(greet("Lola"))

#EX3

def check_even_odd(nbr):
  if nbr % 2 == 0:
    return "Even"
  else:
    return "Odd"

print(check_even_odd(7))

#EX4

def sum_list(numbers):
  total = 0
  for n in numbers:
      total += n
  return total

numbers = [1,3,3]
print(sum_list(numbers))

#EX5

def print_days():
  days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
  for day in days:
    print(day)

print_days()

#EX6

def check_sign(nbr):
  if nbr > 0:
    return "Positive"
  elif nbr < 0:
    return "Negative"
  else:
    return "Zero"

print(check_sign(8))

#EX7

def repeat_word(a,b):
  for r in range(b):
    print(a)

repeat_word("Holà",7)