# -*- coding: utf-8 -*-
"""Ex_Functions_Intermediate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAs24qct5rtMBJ_TECnKOn69oYafzMzX
"""

#EX1

def find_largest(numbers):
  for n in numbers:
    return max(numbers)

numbers = [1,3,7]
find_largest(numbers)

#EX2

def check_letter(word,b):
  for w in word:
    if w == b:
      return "True"
  if w != b:
      print("False")


check_letter("bijou","j")

def count_to_number(nbr):
  for n in range(1,nbr+1):
       print(n)

count_to_number(8)